### ISSUE TITLE
 change url of the ghost blog site in docker container

### ISSUE THREAD

**Issue by shabina-farnaaz** [docker-library/ghost#252] opened 2021-03-31 16:47 UTC
Hello,

I have spin up docker containers using docker-ghost image. The current url is http://host-ip:3008, I want to change it to http://cname.com . I have used docker run to create the ghost image containers, did not use docker compose or stack. Now i want to change the url of the ghost blog site that is hosted on this container. How can I do it? how do i change the ghost config using docker setup? Any help would be appreciated. thank you.

**Comment by pascalandy** [comment] 2021-03-31 16:49
You should search previous issues :-p
per example: https://github.com/docker-library/ghost/issues/211

**Comment by acburdine** [comment] 2021-03-31 16:51
closing as a duplicate of a few similar issues - https://github.com/docker-library/ghost/issues/184 is likely the most helpful in this instance

**Closed by acburdine** 2021-03-31 16:51 UTC
