### ISSUE TITLE
no permanent config with the current image

### ISSUE THREAD

**Issue by smoebody** [docker-library/ghost#74] opened 2017-08-04 13:04 UTC
I just migrated my blogs running ghost 0.11.x to 1.5 with this image and i am afraid that making the `config.production.json`permanent is not possible anymore.

One cannot bind a volume to `/var/lib/ghost` anymore, otherwise ghost refuses to start since essential files and folders are missing. This makes it impossible to apply settings such as mail configuration permanently to the config-file.

**Comment by acburdine** [comment] 2017-08-04 13:15
@smoebody as has been said in #73 - Ghost 1.0 is able to be configured with environment variables, see [the docs](https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables).

Closing as a duplicate of #73

**Closed by acburdine** 2017-08-04 13:15 UTC
