### ISSUE TITLE
Arm64 Fails to run docker No module found sqlite3

### ISSUE THREAD

**Issue by L3rchal** [docker-library/ghost#159] opened 2018-10-13 17:49 UTC
Guys looks like issue https://github.com/docker-library/ghost/issues/98 is back again 😞 
Image builded manually (latest github version)

Platform: Linux 4.4.126-rockchip-ayufan-239 #1 SMP Sun May 27 18:38:24 UTC 2018 aarch64 GNU/Linux

Error log:
```
Knex: run $ npm install sqlite3 --save Error: Cannot find module 'sqlite3' at 
Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Client_SQLite3._driver 
(/var/lib/ghost/versions/2.2.2/node_modules/knex/lib/dialects/sqlite3/index.js:79:12) at 
Client_SQLite3.initializeDriver (/var/lib/ghost/versions/2.2.2/node_modules/knex/lib/client.js:254:26) at 
Client_SQLite3.Client (/var/lib/ghost/versions/2.2.2/node_modules/knex/lib/client.js:115:10) at new 
Client_SQLite3 (/var/lib/ghost/versions/2.2.2/node_modules/knex/lib/dialects/sqlite3/index.js:62:20) at 
Knex (/var/lib/ghost/versions/2.2.2/node_modules/knex/lib/index.js:60:34) at Object. 
(/var/lib/ghost/versions/2.2.2/core/server/data/db/connection.js:33:20) at Module._compile 
(module.js:653:30) at Object.Module._extensions..js (module.js:664:10) at Module.load 
(module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3) 
at Module.require (module.js:597:17)
```

**Comment by L3rchal** [comment] 2018-10-14 12:42
^ This fails after building a running `apline` image.

`Debian` I wasn't even able to build due ` Failed to fetch https://security.debian.org/debian-security/dist/jessie/update/InRelease Uanble to find expected entry 'main/binary-arm64/Packages' in release file (Wrong sources.list)
` error.

**Comment by yosifkit** [comment] 2018-10-15 23:13
Duplicate of #157.

**Closed** 2018-10-16 19:10 UTC
Labels: Issue
