### ISSUE TITLE
tar: /var/lib/ghost/content.orig: Cannot open

### ISSUE THREAD

**Issue by ofstudio** [docker-library/ghost#155] opened 2018-10-05 19:29 UTC
**Host system**
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Docker version**
```bash
$ docker -v
Docker version 18.06.1-ce, build e68fc7a

$ docker info
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 41
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.38-std-1
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956GiB
Name: feynman.scaleway
ID: KIQY:ET7I:ZF2Y:YKXC:KIKW:R46G:JDSX:PMR5:3XNC:5NLD:DOKV:634Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**docker-compose.yaml**
```yaml
version: '3'
services:

  ghost:
    image: ghost:2.2
    restart: unless-stopped
    networks:
      - web
      - default
    volumes:
      - /srv/ghost:/var/lib/ghost
networks:
  web:
    external: true
```

**Container log**
```bash
$ docker logs ghost_ghost_1
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

**Comment by wglambert** [comment] 2018-10-05 19:41
Duplicate of https://github.com/docker-library/ghost/issues/69#issuecomment-319741569

https://github.com/docker-library/docs/tree/master/ghost#ghost-011x--ghost-1xx
Use `/var/lib/ghost/content`

**Closed by wglambert** 2018-10-05 19:41 UTC
Labels: question
