### ISSUE TITLE
Ghost 4.2.1 image Ghost startup fails with node error

### ISSUE THREAD

**Issue by kincsescsaba** [docker-library/ghost#255] opened 2021-04-16 17:48 UTC
Hi,
I get the following:
Error relocating /var/lib/ghost/versions/4.2.1/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node: fcntl64: symbol not found

Somewhere I read that this might be fixed by adding a glibc install to the image

This error occurred when 4.2.1 version came out

**Comment by kincsescsaba** [comment] 2021-04-16 20:12
UPDATE: I created a temporary fix building a modified Dockerfile locally, adding a libbsd install. Please check what should be a final solution for this issue so that I can switch back to the official image!

**Comment by pascalandy** [comment] 2021-04-16 20:26
Are you using the Debian or the alpine docker image?

**Comment by kincsescsaba** [comment] 2021-04-16 20:29
Alpine

**Comment by tianon** [comment] 2021-04-23 18:46
I can't reproduce with either the latest `ghost:4-alpine` or `ghost:4.2.1-alpine`: :confused: (maybe you can provide more details?)

```console
$ docker pull ghost:4-alpine
4-alpine: Pulling from library/ghost
Digest: sha256:84003130a249b5beb2e9ece25f28a3c30f581b5ee03add756e25566d292f9f9f
Status: Image is up to date for ghost:4-alpine
docker.io/library/ghost:4-alpine
$ docker run -it --rm ghost:4-alpine
...
[2021-04-23 18:45:27] INFO Ghost booted in 4.995s

$ docker pull ghost:4.2.1-alpine
4.2.1-alpine: Pulling from library/ghost
Digest: sha256:ef9c288047ac7f8b684fd62e54b2c5c9c00394336ea56fd20e7aa990af10c4e0
Status: Image is up to date for ghost:4.2.1-alpine
docker.io/library/ghost:4.2.1-alpine
$ docker run -it --rm ghost:4.2.1-alpine
...
[2021-04-23 18:46:40] INFO Ghost booted in 5.518s
```

**Comment by wglambert** [comment] 2021-06-30 17:23
Closing since this isn't reproducible and assuming it's resolved

**Closed by wglambert** 2021-06-30 17:23 UTC
