### ISSUE TITLE
how can i upgrade to 2.x 

### ISSUE THREAD

**Issue by callmesoul** [docker-library/ghost#162] opened 2018-11-02 08:15 UTC
now i use 1.x .
how can i upgrade to 2.x ;
i try into container and change node user run  `ghost update` is fail;

and i try `docker exec -u node myblog ghost update`
but:

```
root@iZwz96uhzqta4rogvdaxupZ:~# sudo docker exec -u node myblog ghost update
sudo: unable to resolve host iZwz96uhzqta4rogvdaxupZ
[08:10:30] Checking for Ghost-CLI updates [started]
[08:10:31] Checking for Ghost-CLI updates [completed]
+ sudo systemctl is-active ghost_undefined
A ProcessError occurred.

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_undefined
/bin/sh: 1: sudo: not found


Exit code: 127


Debug Information:
    OS: linux, v4.4.0-85-generic
    Node Version: v6.13.0
    Ghost-CLI Version: 1.9.7
    Environment: production
    Command: 'ghost update'

Additional log info available in: /home/node/.ghost/logs/ghost-cli-debug-2018-11-02T08_10_31_915Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://docs.ghost.org/docs/troubleshooting#section-cli-errors for troubleshooting.
```

**Comment by acburdine** [comment] 2018-11-02 13:16
Closing as a duplicate of #147 and #158 - see the note here: https://hub.docker.com/_/ghost/ on "Upgrading Ghost"

**Closed by acburdine** 2018-11-02 13:16 UTC
Labels: question
