### ISSUE TITLE
Container can't start - Segmentation fault error

### ISSUE THREAD

**Issue by Demon-DK** [docker-library/ghost#129] opened 2018-04-30 23:56 UTC
Trying to run ghost container with such command line:
`docker run -d --network My-network --name My-ghost -p 3001:2368 -v ghost_data:/var/lib/ghost/content ghost:1.22.4-alpine`

Without success, container can't start.

In logs there are only one error:
`/usr/local/bin/docker-entrypoint.sh: line 22:    53 Segmentation fault      knex-migrator-migrate --init --mgpath "$GHOST_INSTALL/current" `

**Comment by tianon** [comment] 2018-04-30 23:58
I can't reproduce here; sounds like image corruption or an issue with your host machine.  I'd recommend clearing out all traces of the `ghost:1.22.4-alpine` image and re-pulling it, then trying again.  Also, I'd suggest checking whether you've got sufficient RAM, CPU, etc.

**Comment by promek** [comment] 2018-05-06 00:14
I have the same problem.
I did a lot of tests, including ghost:1.22.5

Host machine is Alpine Linux v3.7
Docker version 17.12.0-ce

**Comment by wglambert** [comment] 2018-05-07 17:27
Is this related at all https://github.com/docker-library/ghost/issues/111

**Comment by Demon-DK** [comment] 2018-05-07 18:30
Yeap, confirm the temporary solution

1. Create own image based on desired Ghost
```
FROM ghost:1.22.4-alpine
RUN apk add --no-cache paxctl && paxctl -cm `which node`
```

2. Then start container based on your previously created imaged

**Comment by promek** [comment] 2018-05-08 13:29
thank you so much.
I created a docker file for 1.22.5
docker pull promek/ghost: 1.22.5
https://github.com/promek/dockers/tree/master/ghost

**Comment by tianon** [comment] 2018-05-11 20:12
Closing in favor of the upstream issue: https://github.com/nodejs/docker-node/issues/588. :+1:

**Closed by tianon** 2018-05-11 20:12 UTC
