### ISSUE TITLE
cannot accesses via SSL this docker images

### ISSUE THREAD

**Issue by ivanhertanto** [docker-library/ghost#191] opened 2019-08-07 15:51 UTC
ghost docker images cannot access SSL, 
image: ghost:2.27.0-alpine

**Comment by wglambert** [comment] 2019-08-07 16:16
https://github.com/docker-library/ghost/issues/165#issuecomment-440852132

- `From what I can find (both by playing with ghost setup ssl, and by exploring the Ghost documentation), Ghost itself doesn't actually support SSL directly, and instead they recommend (and their tools can help configure) terminating SSL in a reverse proxy like NGINX or Apache, which seems pretty reasonable (especially for a production deployment, where you likely want a reverse proxy in front of Node.js anyhow).`

**Comment by tianon** [comment] 2019-08-08 23:49
Closing as a duplicate of #165

**Closed by tianon** 2019-08-08 23:49 UTC
Labels: question
