### ISSUE TITLE
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory 

### ISSUE THREAD

**Issue by twiceyuan** [docker-library/ghost#69] opened 2017-08-02 07:03 UTC
I use docker compose to create it, the configuration file approximately is:

```
services:
  blog:
    image: "ghost:latest"
    ports:
      - 1984:2368
    volumes:
      - [data directory]:/var/lib/ghost
```

The `data directory` is a new directory and I have full permissions. But it seems failed, the logs show this:

```
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

And after this I can see the `content` directory was created in the `data directory`. Is anything wrong?

**Comment by weipah** [comment] 2017-08-02 09:11
I ran into the same issue. 

Happens only, when I mount an empty folder to /var/lib/ghost
When I don't mount a volume it works.

I tried
`sudo docker run -it --name ghost-blog-1.0 -v /var/www/ghost:/var/lib/ghost -p 2368:2368 ghost:1.0`

**Comment by pascalandy** [comment] 2017-08-02 17:27
I solved it.

## Explaination

I took a look at the Dockerfile. You can see [here](https://github.com/docker-library/ghost/blob/master/1.0/alpine/Dockerfile#L20) that the Docker Ghost 1.0 now use `/var/lib/ghost/content` and NOT `/var/lib/ghost/`

When I run it locally:

docker run -d \
--name ghostone \
-p 3001:2368 \
-v /Users/myusername/Documents/gstdatatest:/var/lib/ghost/content \
ghost:1.0.2-alpine

## Docs
I would do a PR on the readme over [here](https://github.com/docker-library/docs/tree/master/ghost).

Please let me know if you guys can replicate :)

Cheers!
Pascal

**Comment by weipah** [comment] 2017-08-03 07:22
Thanks, @pascalandy that was a real stupid one! *sigh*

Although now I'm running into another issue, but I don't think that is related.

> tar: themes/casper: Cannot utime: Operation not permitted

**Comment by weipah** [comment] 2017-08-03 11:48
I figured the problem is that I'm mapping a local drive from windows machine and tar somehow cannot update the access/read/edit (utime) time on the filesystem with tar.

For now I went on a simpler approach for the copying of the files in the entrypoint-script.
```
if [[ "$*" == node*current/index.js* ]] && ! ls $GHOST_CONTENT/* 1>/dev/null 2>&1; then
  cp -R $GHOST_INSTALL/content.orig/* $GHOST_CONTENT/
  knex-migrator-migrate --init --mgpath "$GHOST_INSTALL/current"
fi
```
Cheers,
Mark

**Comment by pascalandy** [comment] 2017-08-04 13:17
I think we should close this issue :)

**Comment by acburdine** [comment] 2017-08-04 13:22
Ok 😄 

A solution has been posted by @pascalandy -> if the issue persists comment and we can reopen or create a new issue.

**Closed by acburdine** 2017-08-04 13:22 UTC
