### ISSUE TITLE
Error with image upload in Alpine 3.0 and 3.1

### ISSUE THREAD

**Issue by leomalaveraG** [docker-library/ghost#198] opened 2019-12-09 16:17 UTC
I'm testing with the recents versions of ghost in alpine and find some bug. 

Scenario : 
traefik proxy 
Ghost 3.1 alpine 
Docker 19.03.5

I try to upload a image in a post or design (cover, publication icon) and the container die before upload finish.

**Comment by leomalaveraG** [comment] 2019-12-09 16:18
**Update:** 
In not alpine version is working well.

**Comment by wglambert** [comment] 2019-12-09 18:48
Can you get the `docker logs` for the Alpine container, if it's not ran with `--rm` it won't be removed on exit

**Comment by wglambert** [comment] 2019-12-10 00:01
I'm not able to reproduce

```console
$ docker run -d -p 2368:2368 --name ghost ghost:alpine
70b866bc0dd34e4ba684c901955acd88b3cdb01b8a0a037f1e4c310ad00a5539
```
Log output when uploading servers.jpg
```console
[2019-12-09 23:58:14] INFO "POST /ghost/api/v3/admin/images/upload/" 201 154ms
[2019-12-09 23:58:14] INFO "GET /content/images/2019/12/servers_1600x900.jpg" 200 7ms
[2019-12-09 23:58:14] INFO "PUT /ghost/api/v3/admin/posts/5deedf6c3b1365000110b1e3/" 200 229ms
[2019-12-09 23:58:37] INFO "PUT /ghost/api/v3/admin/posts/5deedf6c3b1365000110b1e3/" 200 201ms
[2019-12-09 23:58:40] INFO "GET /test/" 200 108ms
[2019-12-09 23:58:41] INFO "GET /content/images/size/w2000/2019/12/servers_1600x900.jpg" 200 52ms
```
The blog post with servers.jpg
![image](https://user-images.githubusercontent.com/26428991/70483288-e22c5d00-1a9c-11ea-984e-d7fda998464b.png)

**Comment by leomalaveraG** [comment] 2019-12-10 03:14
![Screen Shot 2019-12-09 at 9 59 28 PM](https://user-images.githubusercontent.com/5674931/70491589-a6f75180-1acf-11ea-9ba7-31bf3cd238a0.png)
![Screen Shot 2019-12-09 at 10 03 12 PM](https://user-images.githubusercontent.com/5674931/70491664-e160ee80-1acf-11ea-869e-e00199468ab0.png)



In the images you can check the log for ghost and reverse proxy. 

Proxy fail when image "finish" the upload and the container restart automatically because die

**Comment by wglambert** [comment] 2019-12-10 17:31
My guess is it's getting OOMkilled or some other fatal error. It could also be something specific with Alpine and your environment that's causing the issue. But by default Alpine uploads images just fine, maybe using the non-alpine variant would be the easiest thing for you. Since Alpine-specific issues aren't uncommon, as it uses a different libc implementation to save space 

https://github.com/docker-library/docs/tree/master/ghost#ghostversion-alpine
>certain software might run into issues depending on the depth of their libc requirements. However, most software doesn't have an issue with this, so this variant is usually a very safe choice.

```console
$ docker images | grep ghost
ghost                                   alpine              7a562dfa21a3        5 days ago          327MB
ghost                                   latest              eadda45eb5e4        5 days ago          394MB
```
Debian is only about 20% bigger

If you want to provide a minimal reproducer I could try probing the issue further

**Comment by pascalandy** [comment] 2020-01-05 03:00
I'm getting a similar issue on Alpine since Ghost V3 and I can't find the reason why the is a bug.

### Ghost v2 on alpine using multi-stage builds:

https://github.com/firepress-org/ghostfire/blob/8d3bb445853785ea9197567582e2e6f55cb9313f/Dockerfile

### Now, I'm using Debian for this reason:

https://github.com/firepress-org/ghostfire/blob/3.0.3-debian/Dockerfile

**Comment by acburdine** [comment] 2020-01-05 22:56
Hey everyone, on first glance this is likely related to https://github.com/TryGhost/Ghost/issues/11129

**Comment by leomalaveraG** [comment] 2020-01-06 01:07
> Hey everyone, on first glance this is likely related to [TryGhost/Ghost#11129](https://github.com/TryGhost/Ghost/issues/11129)

Hi! 

Tested with security profile unconfirmed  [https://github.com/TryGhost/Ghost/issues/11129#issuecomment-560033392](Related Here)

Is working with unconfirmed profile, but with a strict security profile does not work.

**Comment by pascalandy** [comment] 2020-01-06 03:08
Thanks for jumping in @acburdine @leomalaveraG .

To be clear, we can confirm this is not an issue related the the Docker image itself. 

So let's follow https://github.com/TryGhost/Ghost/issues/11129 and we will close this issue after.

**Comment by Slethen** [comment] 2020-01-07 14:13
I have the same issue with the latest ghost:3-alpine, when a image finishes uploading the ghost session restarts. Changing my docker-compose file to pull ghost:latest got it working for me.

I'm using a pretty clean VPS hosted with Digital Ocean running Ubuntu 18.04.3 LTS.

Thought it was worth mentioning!

**Comment by pascalandy** [comment] 2020-04-25 19:03
I want to confirm I still have the same behavior. 
even after this issue TryGhost/Ghost#11129 is closed. So I conclude that on **debian**, thing are cool.

It looks there is something fishy with alpine about this glitch @leomalaveraG found

> TryGhost/Ghost#11129 (comment)
> Is working with unconfirmed profile, but with a strict security profile does not work.

**Comment by pascalandy** [comment] 2020-08-11 22:53
Hello folks,
I was running Ghost on debian for while because of this bug. I gave alpine another shot. It's all running smoothly just as before 👍 .

- ghost:3.29.1
- cli:1.14.1
- node:12.18.3-alpine3.12
- alpine:3.12

You can see my dockerfile [here](https://github.com/firepress-org/ghostfire/blob/b56e48eebcde36223045d29af41d7f4f7b6cb925/Dockerfile).

To conclude, I think we can close this issue 🥳

**Comment by tianon** [comment] 2020-08-11 22:55
Nice, thanks for the confirmation! :+1:

**Closed by tianon** 2020-08-11 22:55 UTC
Labels: question
