### ISSUE TITLE
arm64v8/ghost (both debian as alpine) not beeing build

### ISSUE THREAD

**Issue by h3rj4n** [docker-library/ghost#157] opened 2018-10-12 17:03 UTC
There are currently only old images available for arm based devices. Jenkins fails for some reason.

I'm trying to build the images local. It seems there is an old bug that causes the builds to fail:
* https://github.com/npm/uid-number/issues/3

I've added `npm config set unsafe-perm true` as solution to the docker file and now it's being build. Is it possible to add this solution to the docker files?

**Comment by yosifkit** [comment] 2018-10-12 17:37
The reason for the build failures on the Debian images is that Debian Jessie (which all the Debian-based node images still use) no longer supports arm64v8 and many other arches since it transitioned  to LTS (https://github.com/docker-library/official-images/pull/4593, https://wiki.debian.org/LTS/, and https://github.com/nodejs/docker-node/pull/863).  So there is nothing we can do to bring these back until node moves their images to Debian Stretch.

As for the Alpine based builds, it seems weird that `unsafe-perm` is required at all since the arm32v6 builds for Alpine work fine. :confused: 

There are up-to-date arm32v7 builds for the Debian images.

**Comment by L3rchal** [comment] 2018-10-13 12:52
Thanks @h3rj4n for quick fix. 🙇

**Comment by tianon** [comment] 2018-10-17 21:15
Looks like this `npm` bug is now filed at https://npm.community/t/old-closed-issue-from-npm-uid-number-error-could-not-get-uid-gid/2697?  (Having trouble determining exactly where `npm` bugs ought to be filed given the archiving of https://github.com/npm/npm and the no-issues on https://github.com/npm/cli.)

Given that this works fine on other architectures (including `arm32v7` and `arm32v6`), I'm inclined to believe this really is just an `npm` bug, and that we ought to wait for them to provide an appropriate fix for it instead of enabling a hacky workaround just for `arm64v8` (the most puzzling part of all being that `arm64v8` seems to be the _only_ architecture affected, which simply doesn't make sense given the bug linked above).

**Comment by tianon** [comment] 2018-10-17 21:37
I did some digging in the image.  I added a bunch of debug statements to `/usr/local/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js`, and it segfaults while invoking `process.setgid(group)` (https://github.com/npm/uid-number/blob/6e9bdb302ae4799d05abf12e922ccdb4bd9ea023/get-uid-gid.js#L19).

This is looking like it's potentially related to https://github.com/npm/uid-number/issues/6.

**Comment by tianon** [comment] 2018-10-17 21:44
Aha, https://github.com/nodejs/docker-node/issues/813 describes these symptoms, especially https://github.com/nodejs/docker-node/issues/813#issuecomment-407322127.

This is failing on `s390x` as well, but _not_ on `ppc64le` or `arm32v6` which is extra bizarre.

The trivial reproducer is to simply run `node /usr/local/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js`, which should output `[ 0, 0 ]` (debugging output), then segfault on affected platforms.

**Comment by tianon** [comment] 2018-10-17 21:44
(If it succeeds, like it does on my local `amd64` box, it should output `{"uid":0,"gid":0}`)

**Comment by pascalandy** [comment] 2018-11-21 17:35
In my Travis builds, ARM builds are working normally using Node V8 and V10.
I think we could close this.

**Comment by L3rchal** [comment] 2018-11-21 23:02
Can this image for amr64v8 get also updated https://hub.docker.com/r/arm64v8/ghost/ 🙏

**Comment by tianon** [comment] 2018-11-22 00:06
Builds are still failing with this same error weird UID-related error (just as described in https://github.com/nodejs/docker-node/issues/813): https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/ghost/

**Comment by pascalandy** [comment] 2018-11-22 15:49
Maybe on Node V8 something is off. But as Ghost now supports V10, I think there is no point trying to solve this issue under V8.

**Comment by lag-linaro** [comment] 2018-12-04 08:11
Still broken unfortunately.  Is anyone trying to actively fix it?

**Comment by tianon** [comment] 2020-05-07 22:19
This has been fixed for a while (likely by our switch from `npm` to `yarn`). :+1:

**Closed by tianon** 2020-05-07 22:19 UTC
Labels: Issue

**Comment by fightforlife** [comment] 2021-12-30 12:22
Is this happening again?
The newest build in the docker hub repo from 12 days ago by doijanky includes a very old version of ghost. Created | 2021-04-19 21:06:47 with ENV GHOST_VERSION=4.2.2

docker pull ghost@sha256:eaf658adc70df6381f16e5693d75ce2829a657af462a1d89cf0787c8ca6489fa
Image ID: sha256:3a8f17cf224c1c91725ad725c5908f337cbb419997c98d997d38795f5eb1207f
from here:
https://github.com/docker-library/repo-info/blob/master/repos/ghost/tag-details.md#ghostalpine

**Comment by tianon** [comment] 2022-01-03 21:42
Yep, looks like `ghost:4.32.0-alpine` is failing to build. :disappointed:

```console
+ npm_config_python=python3 su-exec node yarn add sqlite3@5.0.2 --force --build-from-source
yarn add v1.22.15
[1/5] Validating package.json...
warning ghost@4.32.0: The engine "cli" appears to be invalid.
[2/5] Resolving packages...
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@1.0.2"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Rebuilding all packages...
error /var/lib/ghost/versions/4.32.0/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /var/lib/ghost/versions/4.32.0/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.18.2 | linux | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@14.18.2 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.2 | linux | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.2 | linux | arm64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
gyp ERR! System Linux 5.11.0-1019-oracle
gyp ERR! command "/usr/local/bin/node" "/var/lib/ghost/versions/4.32.0/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=python3"
gyp ERR! cwd /var/lib/ghost/versions/4.32.0/node_modules/sqlite3
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /var/lib/ghost/versions/4.32.0/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=python3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/lib/ghost/versions/4.32.0/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 5.11.0-1019-oracle
node-pre-gyp ERR! command "/usr/local/bin/node" "/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/lib/ghost/versions/4.32.0/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /var/lib/ghost/versions/4.32.0/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/lib/ghost/versions/4.32.0/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=python3' (1)
```
