### ISSUE TITLE
Copy Custom theme

### ISSUE THREAD

**Issue by Rahulsharma0810** [docker-library/ghost#193] opened 2019-09-06 14:42 UTC
I want to use a custom theme in ghost image

```
FROM ghost:latest

ARG GHOST_INSTALL="/var/lib/ghost"

RUN mkdir -p $GHOST_INSTALL/content/adapters/storage/ && \
    npm install ghost-storage-adapter-s3 && \
    cp -r ./node_modules/ghost-storage-adapter-s3 /var/lib/ghost/current/core/server/adapters/storage/s3

RUN apt-get update -y && apt-get upgrade -y && \
   apt-get install git -y

RUN git clone -b master https://github.com/godofredoninja/simply.git $GHOST_INSTALL/content/themes/simply

RUN apt-get purge git -y

# Define default command
CMD [ "node", "current/index.js" ]
```
But when I boot container it always comes with Casper default theme.

Is there any way to overwrite this?

**Comment by tianon** [comment] 2019-09-06 16:31
Duplicate of #175

**Closed by tianon** 2019-09-06 16:31 UTC
