### ISSUE TITLE
I cannot  do an Healthcheck since v3.3.0

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#208] opened 2020-01-30 23:42 UTC
Hi,

I've been running ghost in a docker service for 2+ years. I use the healthcheck attributes but it does not work anymore.

```
### config example

docker service create \
	--name=${CTN_ghost} --hostname=${CTN_ghost} \
	...
	--health-start-period="30s" --health-interval="12s" --health-timeout="10s" --health-retries="3" \
	--health-cmd "curl -fail http://localhost:2368/blog || exit 1" \
```

As I used the debian ghost's image, I did 

```
docker exec -it ghost bash
```

But I can't do anything at all!? Not even `ls`. So of course my healthcheck is not working anymore.

I guess it's the way `node:12-buster-slim` is made, but I don't understand how we are supposed to work now. When I build with `node:10.17-slim` it's all good.

Thanks in advance!

**Comment by tianon** [comment] 2020-02-01 00:28
Not sure why you couldn't do `ls` in your `docker exec` (I can't reproduce that one), but your in-container healthcheck command is definitely failing due to https://github.com/nodejs/docker-node/issues/1185 (the `node` base image was only including `curl` as a side-effect, which they've now fixed -- we never intentionally included `curl` explicitly in this image either, so that side-effect carries forward).

I'd recommend using a separate container (or other external process like `consul`, https://github.com/prometheus/blackbox_exporter, etc) to perform your healthcheck on the container externally.

If you're determined to have `curl` inside your `ghost` container, I'd recommend something like:

```dockerfile
FROM ghost:3
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
```

Alternatively, if your use case allows for an Alpine-based container, you could switch to the `-alpine` variants which come with Busybox's `wget` built-in which you could use instead.

**Comment by pascalandy** [comment] 2020-02-01 03:00
Thanks for confirming, it's very helpful. I'll add curl in my image.
Regarding alpine, we are all waiting for [this issue](https://github.com/docker-library/ghost/issues/208) to be resolve by the ghost team.

**Closed** 2020-02-01 03:00 UTC
