### ISSUE TITLE
ghost not reachable when using NODE_ENV: development

### ISSUE THREAD

**Issue by SkyGuardian42** [docker-library/ghost#97] opened 2017-10-19 16:41 UTC
I'm using the ghost:1.14 image with docker compose, and using it in production works;
```
version: '3.1'

services:

  ghost:
    container_name: ghost
    image: "ghost:1.14"
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      NODE_ENV: production
```
and when I change the NODE_ENV to development, the log I get is
```
$ docker-compose up
Recreating ghost ...
Recreating ghost ... done
Attaching to ghost
ghost    | [2017-10-19 16:37:49] INFO Creating table: posts
ghost    | [2017-10-19 16:37:49] INFO Creating table: users
ghost    | [2017-10-19 16:37:49] INFO Creating table: roles
ghost    | [2017-10-19 16:37:49] INFO Creating table: roles_users
ghost    | [2017-10-19 16:37:49] INFO Creating table: permissions
ghost    | [2017-10-19 16:37:49] INFO Creating table: permissions_users
ghost    | [2017-10-19 16:37:49] INFO Creating table: permissions_roles
ghost    | [2017-10-19 16:37:49] INFO Creating table: permissions_apps
ghost    | [2017-10-19 16:37:49] INFO Creating table: settings
ghost    | [2017-10-19 16:37:49] INFO Creating table: tags
ghost    | [2017-10-19 16:37:49] INFO Creating table: posts_tags
ghost    | [2017-10-19 16:37:49] INFO Creating table: apps
ghost    | [2017-10-19 16:37:49] INFO Creating table: app_settings
ghost    | [2017-10-19 16:37:49] INFO Creating table: app_fields
ghost    | [2017-10-19 16:37:49] INFO Creating table: clients
ghost    | [2017-10-19 16:37:49] INFO Creating table: client_trusted_domains
ghost    | [2017-10-19 16:37:49] INFO Creating table: accesstokens
ghost    | [2017-10-19 16:37:49] INFO Creating table: refreshtokens
ghost    | [2017-10-19 16:37:49] INFO Creating table: subscribers
ghost    | [2017-10-19 16:37:49] INFO Creating table: invites
ghost    | [2017-10-19 16:37:49] INFO Creating table: brute
ghost    | [2017-10-19 16:37:49] INFO Model: Post
ghost    | [2017-10-19 16:37:50] INFO Model: Tag
ghost    | [2017-10-19 16:37:50] INFO Model: Client
ghost    | [2017-10-19 16:37:50] INFO Model: Role
ghost    | [2017-10-19 16:37:50] INFO Model: Permission
ghost    | [2017-10-19 16:37:51] INFO Model: User
ghost    | [2017-10-19 16:37:51] INFO Relation: Role to Permission
ghost    | [2017-10-19 16:37:52] INFO Relation: Post to Tag
ghost    | [2017-10-19 16:37:52] INFO Relation: User to Role
ghost    | [2017-10-19 16:37:52] INFO Finished database migration!
ghost    | [2017-10-19 16:37:55] INFO Ghost is running in development...
ghost    | [2017-10-19 16:37:55] INFO Listening on: 127.0.0.1:2368
ghost    | [2017-10-19 16:37:55] INFO Url configured as: http://localhost:2368/
ghost    | [2017-10-19 16:37:55] INFO Ctrl+C to shut down
ghost    | [2017-10-19 16:37:55] INFO Ghost boot 3.316s
```
but when I try to access ghost through the browser now, I get the error `ERR_EMPTY_RESPONSE` in Chrome. How can I fix this so I can develop themes using docker? Or am I approaching enabling development mode wrong?

**Comment by acburdine** [comment] 2017-10-21 16:22
So the Ghost-CLI docker container is built to only contain a config.production.json. However, it is still _possible_ to run it in development, it just requires an extra environment variable: `server__host: 0.0.0.0` -> this makes it so the docker container will allow incoming connections from outside the container.

Going to close this though as it's intentional and not a bug :)

**Closed by acburdine** 2017-10-21 16:22 UTC
